baseURL = '/'
languageCode = 'en-us'
title = 'Rima Technologies'
theme = 'munix'

relativeURLs = true
uglyURLs = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
    
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Workshop"
        url = "/workshop/"
        weight = 2
    [[menu.main]]
        name = "Resources"
        url = "/resources/"
        weight = 3
    [[menu.main]]
        name = "Writeups"
        url = "/writeups/myfirstwriteup"
        weight = 4
